### ISSUE TITLE
Support library 23.1 update breaks swipe to remove

### ISSUE THREAD

**Issue by dream09** [iPaulPro/Android-ItemTouchHelper-Demo#20]
If you update build.grade to use API 23 and associated dependencies, when swiping an item from the recycler view a gap can then appear when scrolling.

![screenshot_20151023-112648](https://cloud.githubusercontent.com/assets/3429866/10690937/12f3c786-797d-11e5-84ee-6f46ea1ac3d5.png)

**Steps to reproduce:**
1. Clone repository
2. Open project using Android Studio
3. Add extra 10 items to strings.xml `<array name="dummy_items">` to give a bigger scrolling list
4. Update build.gradle to use API 23

```
apply plugin: 'com.android.application'

android {
  compileSdkVersion 23
  buildToolsVersion "23.0.1"

  defaultConfig {
    applicationId "co.paulburke.android.itemtouchhelperdemo"
    minSdkVersion 16
    targetSdkVersion 23
    versionCode 3
    versionName "1.1"
  }
}

dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])
  compile 'com.android.support:design:23.1.0'
  compile 'com.android.support:recyclerview-v7:23.1.0'
}
```

**Comment by AkshayChordiya** [comment]
@dream09 
Same issue here. I hope it is fixed soon.

**Comment by nor13** [comment]
The bug has been fixed, it works fine in 23.1.1.

**Comment by dream09** [comment]
@nor13 
Thanks for the update, just tested and all good again using 23.1.1.

**Comment by AkshayChordiya** [comment]
@dream09 
Great! Thank you.

**Comment by hatpick** [comment]
Hello guys,

I still see the same problem with 23.1.1 any solution?

**Comment by MichaelObi** [comment]
Same problem in 23.1.1.

**Comment by jaredsburrows** [comment]
Update to `23.2.1`
